---
# Variable setup.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Define nginx_user.
  set_fact:
    nginx_user: "{{ __nginx_user }}"
  when: nginx_user is not defined

# Passenger repository setup.
- name: Add Passenger apt key.
  become: yes
  become_method: sudo
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 561F9B9CAC40B2F7
    state: present

- name: Add apt HTTPS capabilities.
  become: yes
  become_method: sudo
  apt: name=apt-transport-https state=present

- name: Add Phusion apt repo.
  become: yes
  become_method: sudo
  apt_repository:
    repo: 'deb https://oss-binaries.phusionpassenger.com/apt/passenger {{ansible_distribution_release}} main'
    state: present
    update_cache: yes

# Nginx and passenger installation.
- name: Install Nginx and Passenger.
  become: yes
  become_method: sudo
  apt: "pkg={{ item }} state=installed"
  with_items:
   - nginx-extras
   - passenger

# Nginx and passenger configuration.
- name: Copy Nginx configuration into place.
  become: yes
  become_method: sudo
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify: restart nginx

- name: Configure passenger virtual host.
  become: yes
  become_method: sudo
  template:
    src: passenger.j2
    dest: /etc/nginx/sites-available/passenger
  notify: restart nginx

- name: Ensure passenger virtual host is enabled.
  become: yes
  become_method: sudo
  file:
    src: /etc/nginx/sites-available/passenger
    dest: /etc/nginx/sites-enabled/passenger
    state: link

- name: Ensure default virtual host is removed.
  become: yes
  become_method: sudo
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

  when: nginx_remove_default_vhost
  notify: restart nginx
